/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactInquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getContactInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'address' : IDL.Text,
          'phoneNumber' : IDL.Text,
          'chatUrl' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getContactInquiryByTimestamp' : IDL.Func([Time], [ContactInquiry], []),
  'getSortedContactInquiries' : IDL.Func(
      [],
      [IDL.Vec(ContactInquiry)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactInquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getContactInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'address' : IDL.Text,
            'phoneNumber' : IDL.Text,
            'chatUrl' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getContactInquiryByTimestamp' : IDL.Func([Time], [ContactInquiry], []),
    'getSortedContactInquiries' : IDL.Func(
        [],
        [IDL.Vec(ContactInquiry)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };